### ISSUE TITLE
Allow the definition of data_model outside a prob model

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#119]
Variabels are actually associated to a default prob model

```
import inferpy as inf
from inferpy import models

import numpy as np
import tensorflow as tf

k, d = 5, 4

w = models.Normal(np.zeros([k,d]), 1, name="w")  # shape = [k,d]

with models.datamodel():
    z = models.Normal(np.zeros(k), 1, name="z") # shape = [N,k] = [1,k] o [k]
    x = models.Normal(tf.matmul(z,w), 1, name="x") # shape = [N,k] @ [k,d] = [N,d] = [1,k] @ [k,d] = [1,d]


print(z.shape)  # (1, 5) 

```

**Comment by jcozar87** [comment]
Related to #114, as it suggested to use a fixed plate size for datamodel to play around, #114 should be implemented after this issue.

I think that can be implemented by assigning the dependency graph to the datamodel instead of to the probmodel. This makes sense, because we are only interested in relations between random variables inside the datamodel, to fix their shape.

**Comment by jcozar87** [comment]
Commit 983eadda02bb0a05f1561521a45dd8059fdb89e4 has been reverted in af61553fd0f16289d8ab86ebaca12b4449dbbab5. We will come back to this issue after #120 and #118. It might give more ideas about possible design modifications. If not, we can reuse code in 983eadda02bb0a05f1561521a45dd8059fdb89e4, or use the idea in [previous comment](https://github.com/PGM-Lab/InferPy/issues/119#issuecomment-462939678)
