### ISSUE TITLE
float32 and float64 problems

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#139]
By default, numpy arrays are defined with dtype==float64 while tensors are float32. Mixing numpy an tensors in the parameters of a model raises some incompatibility errors. Consider to:

- either show a custom exception explaining that numpy arrays should be defined as float32 
- or make this conversion of the parameters automatically

**Comment by jcozar87** [comment]
We have determined to use always float32 dtypes for arguments of Random Variables and inferpy Parameters.

The reason is that some distributions, as Multinomial, does not accept float64 dtypes. Also, interger expected arguments work also if used float dtypes. This way, we always cast numeric arguments to float32.

In the future we can parametrize this in a json, similarly than it is done in keras.
