### ISSUE TITLE
Multinomial batch shape

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#142]
Batch shape is not set properly in Multinomial. This might affect to others with complex
parameters or with event shep

```
x = inf.Multinomial(total_count = 2, logits = [0., 0., 0.])

x.event_shape   # 3
x.batch_shape   # 3     (should be 1)
x.sample_shape  # [] 
```

**Comment by rcabanasdepaz** [comment]
Another problem in multivariate normal:

```

x = inf.MultivariateNormalDiag(loc=[1., -1], 
                               scale_diag=[1, 2.],
                               batch_shape=[3,2],
                               sample_shape=100)


x.event_shape   #  2  ok
x.batch_shape   #  3 but should should be 3,2 
x.sample_shape  #  100   ok
```

**Comment by jcozar87** [comment]
The problem is related with the input sanitize function. It suposes that every argument, but name and sample_shape, must have the same dimension. Therefore, for distributions like multinomial, some arguments are broadcasted incorrectly.

We have decided to remove the functionallity in the  input sanitize function mostly, and rely on argument cleaning from **edward2**. We will use such function only to transform Random Variables from edward2 and inferpy to tensors (using `tf.convert_to_tensor`) when are used as parameters inside of a list structure. In the following this decision is explained:

For some distributions, like `Categorical`, it is common to use as arguments other distributions for the `probs` argument, i.e.: `[distribution_a, 1 - distribution_a]`. Therefore, we still want to have this functionality in Inferpy, but as discussed before the general behaviour of broadcasting every argument is wrong.

**Comment by jcozar87** [comment]
Moreover, as a consequence, the possibility of using `batch_shape` as argument must be removed, as broadcast is not applied for any argument anymore.
