### ISSUE TITLE
sampling efficiency from prior model

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#173]
Sampling a large number of samples from variables in data model takes much.

```
@inf.probmodel
def linear_reg(d):
    w0 = inf.Normal(0, 1, name="w0")
    w = inf.Normal(tf.zeros([d,1]), 1, name="w")

    with inf.datamodel():
        x = inf.Normal(tf.ones([d]), 2, name="x")
        y = inf.Normal(w0 + x @ w, 1.0, name="y")

m = linear_reg(d=2)
m.prior(["x", "y"], data={"w0":0, "w":[[2],[1]]}).sample(1000)
```

Could we improve the efficiency if we just replicate variables in the data model and not those
outside? Or maybe make possible both behaviours?

**Comment by jcozar87** [comment]
We are generating the samples in just one `session.run`. The efficiency issue comes from compact the result into a dict in the form `var_name: samples`, because the result of the `session.run` is a list of `var_name: samples`, where the size of the samples (of each element in the list) is the plate size (1 for not expanded models).

**Comment by rcabanasdepaz** [comment]
Improved efficiency by adding a parameter `size_datamodel` at probmodel.prior().

See commit: a133d224aacad5ae766a9bb604b8b95175e5e468
