### ISSUE TITLE
make MixtureSameFamily to accept Inferpy RVs

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#190]
Random Variables of type `MixtureSameFamilly' only accepts objects of type tfd:

```
import tensorflow_probability as tfp
import inferpy as inf

inf.MixtureSameFamily(mixture_distribution=tfp.distributions.Categorical(logits=[0.,0.]), 
                      components_distribution=tfp.distributions.Normal(loc=[0.,0.], scale=[1.,1.])
                      )

```

Modify it to accept inferpy RVs, for example:

```
inf.MixtureSameFamily(mixture_distribution=inf.Categorical(logits=[0.,0.]),
                      components_distribution=inf.Normal(loc=[0.,0.], scale=[1.,1.])
                      )
```

There might be other RV affected with this.

**Comment by jcozar87** [comment]
The distributions Mixture and MixtureSameFamily have been removed from inferpy, and the distribution MixtureGaussian has been included.

In order to make it work, this distribution encapsulates a tfp.distributions Categorical and a list of tfp.distributions.Normal distributions.

Closed in #90f8028ddc32079464094faef3525bc084b7533c.
